Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 114, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 26, in main
    data_dict = np.load(DATA_DIR + filename, allow_pickle=True).item()
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/clusterfs/stratus/dromps/wrf_fan2018/Supersaturation/Supersaturation/filtered_data_dict_v2.npy'
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/matplotlib/colors.py:1110: RuntimeWarning: invalid value encountered in less_equal
  mask |= resdat <= 0
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/matplotlib/colors.py:1110: RuntimeWarning: invalid value encountered in less_equal
  mask |= resdat <= 0
Polluted
-0.027727851303300736 0.1287482628772485 0.405311620865788
# pts total: 8703546
max: 49868.360616704085
# pts ss > 2%: 2824400
Number of points in Q1: 7876513
Number of points in Q2: 0
Number of points in Q3: 0
Number of points in Q4: 1533235

Domain: -34554.91368141663 49868.360616704085
Range: -45.968933 20.070312
Unpolluted
-0.030736765433959482 1.2176870323125795 0.32400674439727783
# pts total: 8163922
max: 9855.259721411849
# pts ss > 2%: 3522187
Number of points in Q1: 7423271
Number of points in Q2: 0
Number of points in Q3: 0
Number of points in Q4: 1429591

Domain: -36071.854476336885 9855.259721411849
Range: -44.57138 54.38872
combined
-0.029149025500370906 0.653394735262627 0.35420601842996907
